// src/logic/teamNames.ts
export const BEER_TEAM_NAMES: string[] = [
  "The Harry Porters",
  "Foamy Mountain",
  "Yeast Mode",
  "Malt Mavericks",
  "Barley & Chill",
  "Lager Legends",
  "Pint of View",
  "Brewed Awakening",
  "Hopportunity Knocks",
  "Foam Sweet Foam",
  "Buzzed Barrels",
  "Golden Suds",
  "Tipsy Taproom",
  "Frothy Fellows",
  "Bitter Bliss",
  "Sip Happens",
  "Stout Scouts",
  "Draft Punks",
  "Hopsicle Stand",
  "The Empire Strikes Bock",
  "Barrel Roll",
  "Beauty and the Yeast",
  "Keg Against the Machine",
  "Hoppy Campers",
  "Stein Time",
  "Don’t Worry, Be Hoppy",
  "Twist and Stout",
  "Keg & Kettle",
  "Hops on the Rocks",
  "The Brews Brothers",
  "Cheerful Cheers",
  "Draft Draftsmen",
  "Hop Star Heroes",
  "Bubbly Barley",
  "Laughing Lager",
  "Giggling Grain",
  "Bad News Beers",
  "Just-In-Stein",
  "Mischief Malt",
  "The Bull-sip Effect",
  "Foam & Fortune",
  "Stout of Control",
  "Gulp Fiction",
  "Hoppy Ending",
  "Obi-Wan Can-nobi",
  "Tipsy Tankards",
  "To Beer or Not To Beer",
  "Dunkel & Dragons",
  "Grain Train",
  "Barley Making It",
  "Barrel Brothers",
  "Game of Foams",
  "Foamy Forecast",
  "Hop-portunity Knocks",
  "Brewed & Confused",
  "Yeast of Eden",
  "Golden Growlers",
  "Yeast of Burden",
  "Hop Goblins",
  "Suds Squadron",
  "Lager Than Life",
  "Tropical Taps",
  "Lazy Lagerheads",
  "Pint of No Return",
  "Grainstorm",
  "Foam Frontiers",
  "Ferment to Be",
  "Hoppy Harbor",
  "Bubble & Barley",
  "Malty Mission",
  "Hops & Dreams",
  "KegQuest",
  "Draft Dynasty",
  "Barrel Bandits",
  "Cheery Chela",
  "Stein Society",
  "Groovy Growlers",
  "Lofty Lager",
  "Brewed Banter",
  "Taproom Titans",
  "Hoppy Highway",
  "Foamy Fellowship",
  "Buzzed Brigade",
  "Brew Voyage",
  "Ale Force One",
  "Suds Station",
  "Hop Springs Eternal",
  "Stout & About",
  "Flight Club",
  "Malt Mischief",
  "Hop & Seek",
  "Foam Horizon",
  "Yeast Feast",
  "Barrel Bliss",
  "Tap Dance",
  "Hop Shelf Heroes",
  "Suds Circus",
  "Barley Party",
  "Foamy Galaxy",
  "Brewtiful Day",
];
